/* ============================================================
   CMMS DATA FILE — Asset Register
   Imported & re-numbered from "Gino Thai MACHINE list_230722.xlsx"
   on 2026-05-14 — 135 machines.
   ID scheme: {DEPT}-{NNN}. Original PM/SM numbers kept in each "notes".
   ============================================================ */
window.CMMS_DB = window.CMMS_DB || {};
window.CMMS_DB.assets = [
  {
    "id": "SUR-001",
    "name": "Protective Film Applicator 3M 1645",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Gerber Coburn",
    "model": "3M 1645",
    "serial": "1800487",
    "installDate": "2008-04-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0001 · Dept: SURFACE · Class: Production · Remark: 22号楼1F车房---- · Original name: 保护胶纸贴膜机"
  },
  {
    "id": "SUR-002",
    "name": "Conventional Polisher Toro-x-2S",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "萨特隆光学设备（中山）有限公司",
    "model": "Toro-x-2S",
    "serial": "1900047",
    "installDate": "2019-06-14",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0002 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Warranty: 2020-05-19 · Original name: 传统抛光机"
  },
  {
    "id": "SUR-003",
    "name": "Conventional Polisher Toro-x-2S",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "萨特隆光学设备（中山）有限公司",
    "model": "Toro-x-2S",
    "serial": "2000639",
    "installDate": "2019-11-25",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0003 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Warranty: 2020-11-24 · Original name: 传统抛光机"
  },
  {
    "id": "SUR-004",
    "name": "Conventional Polisher Toro-x-2S",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "萨特隆光学设备（中山）有限公司",
    "model": "Toro-x-2S",
    "serial": "2000640",
    "installDate": "2019-11-25",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0004 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Warranty: 2020-11-24 · Original name: 传统抛光机"
  },
  {
    "id": "SUR-005",
    "name": "Conventional Polisher Toro-X-2S, 2-head, second-hand",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 65,
    "manufacturer": "Satisloh Asia Limited",
    "model": "Toro-X-2S, 2-head, second-hand",
    "serial": "1800593",
    "installDate": "2017-06-14",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0005 · Dept: SURFACE · Class: Production · Record status: Expried · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Original name: 传统抛光机"
  },
  {
    "id": "SUR-006",
    "name": "Laser Marking Machine Lens-engrarer-Lc",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Satisloh Asia Limited",
    "model": "Lens-engrarer-Lc",
    "serial": "1801890",
    "installDate": "2010-12-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0006 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 0.03 · Working condition: With computer · Remark: 22号楼1F车房---- · Original name: 激光打标机"
  },
  {
    "id": "SUR-007",
    "name": "Polisher Torilab",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "OptoTech Optikmaschinen GmbH",
    "model": "Torilab",
    "serial": "1900012",
    "installDate": "2019-02-21",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0007 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Warranty: 2019-01-05 · Remark: 保质期12个月，到货2018年10月8日 · Original name: 抛光机"
  },
  {
    "id": "SUR-008",
    "name": "Polisher Torilab",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Other Site",
    "criticality": "High",
    "status": "Running",
    "health": 65,
    "manufacturer": "OptoTech Optikmaschinen GmbH",
    "model": "Torilab",
    "serial": "1900013",
    "installDate": "2019-02-21",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0008 · Dept: SURFACE · Class: Production · Record status: Expried · Volt: 380 · kVA: 1 · Working condition: 手动，温度10-15°C · Warranty: 2019-01-05 · Remark: 保质期12个月，到货2018年10月8日 · Original name: 抛光机"
  },
  {
    "id": "SUR-009",
    "name": "Blocking Oven D-Blocker-01-900-24, manual",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Satisloh Asia Limited",
    "model": "D-Blocker-01-900-24, manual",
    "serial": "1802325",
    "installDate": "2016-08-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0009 · Dept: SURFACE · Class: Production · Volt: 220 · kVA: 2.4 · Working condition: 手动，温度10-15°C · Remark: 22号楼1F车房---- · Original name: 上盘炉"
  },
  {
    "id": "SUR-010",
    "name": "Blocking Oven semi-automatic, SPL-2014",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "中山市赛弛光学设备有限公司",
    "model": "semi-automatic, SPL-2014",
    "serial": "1802324",
    "installDate": "2017-02-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0010 · Dept: SURFACE · Class: Production · Volt: 220 · kVA: 2.4 · Working condition: 手动，温度10-15°C · Warranty: 2018-02-01 · Original name: 上盘炉"
  },
  {
    "id": "SUR-011",
    "name": "Polisher CCP-Swift",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Schneider",
    "model": "CCP-Swift",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0011 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1.5 · Working condition: 手动，温度10-15°C · Original name: 抛光机"
  },
  {
    "id": "SUR-012",
    "name": "Flash-Plus",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "OptoTech Optikmaschinen GmbH",
    "model": "Flash-Plus",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0012 · Dept: SURFACE · Class: Production · Volt: 400 · kVA: 8 · Working condition: 温度 20°C"
  },
  {
    "id": "SUR-013",
    "name": "Flash-Plus",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "OptoTech Optikmaschinen GmbH",
    "model": "Flash-Plus",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0013 · Dept: SURFACE · Class: Production · Volt: 400 · kVA: 8 · Working condition: 温度 20°C"
  },
  {
    "id": "SUR-014",
    "name": "Chiller",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Down",
    "health": 15,
    "manufacturer": "Anges",
    "model": "AC-10D",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0001 · Dept: SURFACE · Class: Support · Record status: Broken · Volt: 380 · kVA: 14"
  },
  {
    "id": "SUR-015",
    "name": "Air conditioner",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "6.15A 900CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0002 · Dept: SURFACE · Class: Support · Volt: 380 · kVA: 4.05"
  },
  {
    "id": "SUR-016",
    "name": "Air conditioner",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "6.15A 900CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0003 · Dept: SURFACE · Class: Support · Volt: 380 · kVA: 4.05"
  },
  {
    "id": "SUR-017",
    "name": "Air conditioner",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "6.15A 900CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0004 · Dept: SURFACE · Class: Support · Volt: 380 · kVA: 4.05"
  },
  {
    "id": "SUR-018",
    "name": "Exhaust Fan 40 CFM",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Kruger",
    "model": "40 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0005 · Dept: SURFACE · Class: Support · Volt: 220 · kVA: 0.06 · Original name: 排气扇"
  },
  {
    "id": "TNT-001",
    "name": "Tinting Machine 12-cylinder",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海殷谷实业有限公司",
    "model": "12-cylinder",
    "serial": "1802274",
    "installDate": "2015-09-29",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0019 · Dept: TINT · Class: Production · Volt: 220 · kVA: 1.8 · Working condition: 温度 95°C · Remark: 准备泰 · Original name: 染色机"
  },
  {
    "id": "TNT-002",
    "name": "Tinting Machine 12-cylinder",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海泛靓实业有限公司",
    "model": "12-cylinder",
    "serial": "1802280",
    "installDate": "2017-05-31",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0020 · Dept: TINT · Class: Production · Volt: 220 · kVA: 1.8 · Working condition: 温度 95°C · Original name: 染色机"
  },
  {
    "id": "TNT-003",
    "name": "Tinting Machine 12-cylinder",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海泛靓实业有限公司",
    "model": "12-cylinder",
    "serial": "1802282",
    "installDate": "2017-05-31",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0021 · Dept: TINT · Class: Production · Volt: 220 · kVA: 1.8 · Working condition: 温度 95°C · Original name: 染色机"
  },
  {
    "id": "TNT-004",
    "name": "Tinting Machine 12-cylinder",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海泛靓实业有限公司",
    "model": "12-cylinder",
    "serial": "1802283",
    "installDate": "2017-05-31",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0022 · Dept: TINT · Class: Production · Volt: 220 · kVA: 1.8 · Working condition: 温度 95°C · Original name: 染色机"
  },
  {
    "id": "TNT-005",
    "name": "Tinting Machine 12-cylinder, timer control",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Other Site",
    "criticality": "High",
    "status": "Running",
    "health": 65,
    "manufacturer": "上海殷谷实业有限公司",
    "model": "12-cylinder, timer control",
    "serial": "1802278",
    "installDate": "2016-06-16",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0023 · Dept: TINT · Class: Production · Record status: Expried · kVA: 0.084 · Remark: 10号楼1F染色---- · Original name: 染色机"
  },
  {
    "id": "TNT-006",
    "name": "Tinting Machine CANTON CT51001-2 12-cylinder",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海康拓光学设备有限公司 (not sure)",
    "model": "CANTON CT51001-2 12-cylinder",
    "serial": "1802272",
    "installDate": "2009-04-24",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0024 · Dept: TINT · Class: Production · kVA: 0.084 · Remark: 10号楼1F染色---- · Original name: 染色机"
  },
  {
    "id": "TNT-007",
    "name": "Exhaust Fan 6000 CFM",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Kruger",
    "model": "6000 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0006 · Dept: TINT · Class: Support · Volt: 380 · kVA: 2.75 · Working condition: Exhaust fan · Remark: Have inverter adjust power · Original name: 排气扇"
  },
  {
    "id": "TNT-008",
    "name": "Exhaust Fan 6000 CFM",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 65,
    "manufacturer": "Kruger",
    "model": "6000 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0026 · Dept: TINT · Class: Production · Record status: Expried · Volt: 380 · kVA: 2.75 · Working condition: Air Make up · Original name: 排气扇"
  },
  {
    "id": "HC-001",
    "name": "Lens Abrasion Tester BLD-323",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "东莞博莱德仪器设备有限公司",
    "model": "BLD-323",
    "serial": "2000005",
    "installDate": "2020-01-06",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0007 · Dept: HC · Class: Support · kVA: 0.084 · Warranty: 2022-01-05 · Original name: 镜片耐磨试验机"
  },
  {
    "id": "HC-002",
    "name": "Industrial Dehumidifier YDA-890E, small",
    "category": "HC",
    "location": "HC Area",
    "building": "Other Site",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "百奥",
    "model": "YDA-890E, small",
    "serial": "1801017",
    "installDate": "2008-05-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0008 · Dept: HC · Class: Support · kVA: 0.084 · Working condition: Water drain out · Remark: 10号楼1F加硬加膜---- · Original name: 工业除湿机"
  },
  {
    "id": "HC-003",
    "name": "Single-Tank Ultrasonic Cleaner SUP6028",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海圣奇清洗机械有限公司",
    "model": "SUP6028",
    "serial": "2000665",
    "installDate": "2019-10-31",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0029 · Dept: HC · Class: Production · Volt: 220 · kVA: 0.03 · Working condition: Work with heater · Original name: 单槽超声波清洗机"
  },
  {
    "id": "HC-004",
    "name": "Coating machine",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "SCL International",
    "model": "CDC-1000 (1)",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0030 · Dept: HC · Class: Production · Volt: 400 · kVA: 10.25"
  },
  {
    "id": "HC-005",
    "name": "OVEN (Medium)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "YITAI",
    "model": "XMTD-8222",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0031 · Dept: HC · Class: Production · Volt: 220 · kVA: 2"
  },
  {
    "id": "HC-006",
    "name": "OVEN (Medium)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "YITAI",
    "model": "XMTD-8222",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0032 · Dept: HC · Class: Production · Volt: 220 · kVA: 2"
  },
  {
    "id": "HC-007",
    "name": "OVEN (Medium)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "YITAI",
    "model": "XMTD-8222",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0033 · Dept: HC · Class: Production · Volt: 220 · kVA: 2"
  },
  {
    "id": "HC-008",
    "name": "OVEN (Medium)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "YITAI",
    "model": "XMTD-8222",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0034 · Dept: HC · Class: Production · Volt: 220 · kVA: 2"
  },
  {
    "id": "HC-009",
    "name": "Clean table",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Hi+ Lab",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0035 · Dept: HC · Class: Production · Volt: 220 · kVA: 0.2"
  },
  {
    "id": "HC-010",
    "name": "Hot plate stirrer",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "LK LAB",
    "model": "HS-20",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0036 · Dept: HC · Class: Production · Volt: 230 · kVA: 0.81 · Working condition: 温度 100°C"
  },
  {
    "id": "HC-011",
    "name": "DI water machine",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "GB5749-85",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0037 · Dept: HC · Class: Production · Volt: 220 · kVA: 0.1"
  },
  {
    "id": "HC-012",
    "name": "Chiller",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Lauda",
    "model": "MC 350",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0009 · Dept: HC · Class: Support · Volt: 230 · kVA: 0.63 · Working condition: R-134a, MP-1154D"
  },
  {
    "id": "HC-013",
    "name": "Chiller",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Lauda",
    "model": "MC 350",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0010 · Dept: HC · Class: Support · Volt: 230 · kVA: 0.63 · Working condition: R-134a, Primer"
  },
  {
    "id": "HC-014",
    "name": "Air purifier",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Xiaomi",
    "model": "AC-M3-CA",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0011 · Dept: HC · Class: Support · Volt: 220 · kVA: 0.08"
  },
  {
    "id": "HC-015",
    "name": "Air purifier",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DL-J12",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0012 · Dept: HC · Class: Support · Volt: 220 · kVA: 0.16"
  },
  {
    "id": "HC-016",
    "name": "Refrigerator",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "Haier HR-DMBX18",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0042 · Dept: HC · Class: Production · Volt: 220 · kVA: 0.27 · Remark: For stock varnish 1-4°C"
  },
  {
    "id": "HC-017",
    "name": "Air conditioner",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "5.50A 800CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0013 · Dept: HC · Class: Support · Volt: 220 · kVA: 1.21 · Remark: Open 24 hrs"
  },
  {
    "id": "HC-018",
    "name": "Electronic Scale",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "JM-F6002",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0044 · Dept: HC · Class: Production · Volt: 220 · kVA: 0.03"
  },
  {
    "id": "HC-019",
    "name": "Exhaust Fan 90 CFM",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Kruger",
    "model": "90 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0014 · Dept: HC · Class: Support · Volt: 220 · kVA: 0.225 · Remark: Refilm · Original name: 排气扇"
  },
  {
    "id": "HC-020",
    "name": "Exhaust Fan 40 CFM",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Kruger",
    "model": "40 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0015 · Dept: HC · Class: Support · Volt: 220 · kVA: 0.06 · Remark: Refilm · Original name: 排气扇"
  },
  {
    "id": "MC-001",
    "name": "3-Phase High-Power Voltage Stabilizer SBW-S-50KVA",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海稳压器厂",
    "model": "SBW-S-50KVA",
    "serial": "1802301",
    "installDate": "2015-05-13",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0047 · Dept: MC · Class: Production · kVA: 0.084 · Working condition: With DLX-1200 · Remark: 22号楼1F车房---- · Original name: 三相大功率补偿式稳压器"
  },
  {
    "id": "MC-002",
    "name": "Industrial Dehumidifier Jinsen CFZ7, large",
    "category": "MC",
    "location": "MC Area",
    "building": "Other Site",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "金森",
    "model": "Jinsen CFZ7, large",
    "serial": "1801016",
    "installDate": "2008-06-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0016 · Dept: MC · Class: Support · kVA: 0.084 · Working condition: Water drain out · Remark: 10号楼1F加硬加膜---- · Original name: 工业除湿机"
  },
  {
    "id": "MC-003",
    "name": "Sandblasting Machine SY-1610A",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海施勇机械设备有限公司",
    "model": "SY-1610A",
    "serial": "2000668",
    "installDate": "2020-08-15",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0049 · Dept: MC · Class: Support · kVA: 0.084 · Working condition: Air filter · Original name: 喷砂机"
  },
  {
    "id": "MC-004",
    "name": "UV detector",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-518",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0050 · Dept: MC · Class: Production · Volt: 220 · kVA: 0.11"
  },
  {
    "id": "MC-005",
    "name": "AR machine",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DLX-1200 (1)",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0051 · Dept: MC · Class: Production · Volt: 400"
  },
  {
    "id": "MC-006",
    "name": "Vaccum cleaner",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0056 · Dept: MC · Class: Production · Volt: 220"
  },
  {
    "id": "MC-007",
    "name": "Air conditioner",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "5.50A 800CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0017 · Dept: MC · Class: Support · Volt: 380 · kVA: 3.62 · Remark: Open 24 hrs"
  },
  {
    "id": "MC-008",
    "name": "Air conditioner",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "9.50A 600CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0018 · Dept: MC · Class: Support · Volt: 220 · kVA: 2.09"
  },
  {
    "id": "MC-009",
    "name": "Air conditioner",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "9.50A 600CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0019 · Dept: MC · Class: Support · Volt: 220 · kVA: 2.09"
  },
  {
    "id": "MC-010",
    "name": "Chiller",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Anges",
    "model": "AC-15",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0020 · Dept: MC · Class: Support · Volt: 380 · kVA: 18.75"
  },
  {
    "id": "MC-011",
    "name": "Exhaust Fan 1,600 CFM",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "1,600 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0021 · Dept: MC · Class: Support · Volt: 220 · kVA: 0.06 · Remark: Sand blasting room · Original name: 排气扇"
  },
  {
    "id": "EDG-001",
    "name": "Air-Cooled Chiller for ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "for ES4",
    "serial": "1800976",
    "installDate": "2000-01-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0022 · Dept: EDGE · Class: Support · Volt: 380 · Working condition: Coolant (Di water) · Remark: 10号楼2F上片---- · Original name: 风冷式冷水机"
  },
  {
    "id": "EDG-002",
    "name": "Air-Cooled Chiller for ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "for ES4",
    "serial": "1800977",
    "installDate": "2000-01-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0023 · Dept: EDGE · Class: Support · Volt: 380 · Working condition: Coolant (Di water) · Remark: 10号楼2F上片---- · Original name: 风冷式冷水机"
  },
  {
    "id": "EDG-003",
    "name": "Frame Scanner FUJI-300TX(TFT)",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Fuji GANKYO KIKAI MFG.CO.LTD",
    "model": "FUJI-300TX(TFT)",
    "serial": "1900088",
    "installDate": "2019-11-12",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0024 · Dept: EDGE · Class: Support · Volt: 220 · kVA: 0.03 · Warranty: 2020-11-11 · Original name: 镜架扫描仪"
  },
  {
    "id": "EDG-004",
    "name": "Edger ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "先利士劳尔光学设备（丹阳）有限公司",
    "model": "ES4",
    "serial": "1802027",
    "installDate": "2016-06-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0061 · Dept: EDGE · Class: Production · Volt: 380 · kVA: 7 · Working condition: Mc no. 1800976 · Warranty: 2017-06-01 · Remark: 10号楼2F上片----旧机 · Original name: 磨边机"
  },
  {
    "id": "EDG-005",
    "name": "Edger ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "萨特隆光学设备（中山）有限公司",
    "model": "ES4",
    "serial": "1802029",
    "installDate": "2017-07-31",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0062 · Dept: EDGE · Class: Production · Volt: 380 · kVA: 7 · Working condition: Mc no. 1800977 · Warranty: 2018-07-06 · Original name: 磨边机"
  },
  {
    "id": "EDG-006",
    "name": "Edger ez fit, with scanner",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "MEI S.r.l.",
    "model": "ez fit, with scanner",
    "serial": "1802022",
    "installDate": "2014-05-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0063 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 5 · Working condition: Water tank built in · Remark: 10号楼2F上片---- · Original name: 磨边机"
  },
  {
    "id": "EDG-007",
    "name": "Blocking Machine 3B Blocker",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Satisloh Asia Limited",
    "model": "3B Blocker",
    "serial": "1802311",
    "installDate": "2015-01-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0064 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.084 · Working condition: 24 DC volt 3.5A · Remark: 10号楼2F上片---- · Original name: 上盘机"
  },
  {
    "id": "EDG-008",
    "name": "Blocking Machine 3B Blocker",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "OMEGA LED LTD",
    "model": "3B Blocker",
    "serial": "1802314",
    "installDate": "2014-09-04",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0065 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.084 · Working condition: 24 DC volt 3.5A · Remark: 10号楼2F上片---- · Original name: 上盘机"
  },
  {
    "id": "EDG-009",
    "name": "Blocking Machine Finish Blocker LS-100",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "青岛韩奥光学有限公司",
    "model": "Finish Blocker LS-100",
    "serial": "2100071",
    "installDate": "2021-03-29",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0066 · Dept: EDGE · Class: Production · Remark: 二手设备 · Original name: 上盘机"
  },
  {
    "id": "EDG-010",
    "name": "Blocking Machine NIDEK CE-9",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海鑫眸医疗器械有限公司",
    "model": "NIDEK CE-9",
    "serial": "1802316",
    "installDate": "2015-10-19",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0067 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.003 · Working condition: 0.5A 2.5W · Remark: 10号楼2F上片---- · Original name: 上盘机"
  },
  {
    "id": "EDG-011",
    "name": "Hand polisher",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海康拓光学设备有限公司",
    "model": "CANTON CT5308",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0068 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.475"
  },
  {
    "id": "EDG-012",
    "name": "Sloting machine",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海康拓光学设备有限公司",
    "model": "CANTON CT5407N",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0069 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.075"
  },
  {
    "id": "EDG-013",
    "name": "Hand grooving machine",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海康拓光学设备有限公司",
    "model": "NH-800ATG",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0070 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.16"
  },
  {
    "id": "EDG-014",
    "name": "Electronic heater",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-320F",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0071 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.75 · Working condition: Hot air mac 110°C"
  },
  {
    "id": "EDG-015",
    "name": "Hand edge grinder",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-35S",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0072 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.15 · Working condition: Water tank built in"
  },
  {
    "id": "EDG-016",
    "name": "Hand edge grinder",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-35S",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0073 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.15 · Working condition: Water tank built in"
  },
  {
    "id": "EDG-017",
    "name": "Hand edge grinder",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-35S",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0074 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.15 · Working condition: Water tank built in"
  },
  {
    "id": "EDG-018",
    "name": "Hand edge grinder",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-35S",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0075 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.15 · Working condition: Water tank built in"
  },
  {
    "id": "EDG-019",
    "name": "Manual Pattern Cutter PICHINA Optical Manual Len Edger PM-7000",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "青岛韩奥光学有限公司",
    "model": "PICHINA Optical Manual Len Edger PM-7000",
    "serial": "2100060",
    "installDate": "2021-03-29",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0076 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.3 · Working condition: Water tank built in · Remark: 二手设备 · Original name: 手动裁形机"
  },
  {
    "id": "EDG-020",
    "name": "Water Circulation System for ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "for ES4",
    "serial": "1802440",
    "installDate": "2000-01-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0077 · Dept: EDGE · Class: Production · kVA: 0.084 · Working condition: Motor included · Remark: 10号楼2F上片---- · Original name: 水循环系统"
  },
  {
    "id": "EDG-021",
    "name": "Water Circulation System for ES4",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "for ES4",
    "serial": "1802441",
    "installDate": "2000-01-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0078 · Dept: EDGE · Class: Production · kVA: 0.084 · Working condition: Motor included · Remark: 10号楼2F上片---- · Original name: 水循环系统"
  },
  {
    "id": "EDG-022",
    "name": "Air conditioner",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "12.5A 600CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0025 · Dept: EDGE · Class: Support · Volt: 220 · kVA: 2.75"
  },
  {
    "id": "EDG-023",
    "name": "Air conditioner",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "12.5A 600CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0026 · Dept: EDGE · Class: Support · Volt: 220 · kVA: 2.75"
  },
  {
    "id": "EDG-024",
    "name": "Kettle (hot boiling water)",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "Hitachi",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0081 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 2.75 · Working condition: 温度 95°C"
  },
  {
    "id": "WH1-001",
    "name": "Air conditioner",
    "category": "WH1",
    "location": "WH1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "7.00A 1000CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0027 · Dept: WH1 · Class: Support · Volt: 380 · kVA: 4.67 · Remark: 1st floor"
  },
  {
    "id": "WH2-001",
    "name": "Air conditioner",
    "category": "WH2",
    "location": "WH2 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0028 · Dept: WH2 · Class: Support · Volt: 220 · kVA: 1.8 · Remark: 2nd floor"
  },
  {
    "id": "WH2-002",
    "name": "Air conditioner",
    "category": "WH2",
    "location": "WH2 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "2.00 KW 600 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0029 · Dept: WH2 · Class: Support · Volt: 220 · kVA: 2.5 · Remark: 2ndfloor"
  },
  {
    "id": "QC-001",
    "name": "Air conditioner",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "5.50A 800CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0030 · Dept: QC · Class: Support · Volt: 380 · kVA: 3.62"
  },
  {
    "id": "QC-002",
    "name": "Weight scale",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0086 · Dept: QC · Class: Production · Volt: 220 · Remark: For Logistic"
  },
  {
    "id": "QC-003",
    "name": "Pad Printing Machine second-handTECO",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Codir转入",
    "model": "second-handTECO",
    "serial": "1802647",
    "installDate": "2014-06-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0087 · Dept: QC · Class: Production · Volt: 220 · kVA: 0.4 · Remark: 10号楼1F质检---- · Original name: 移印机"
  },
  {
    "id": "QC-004",
    "name": "Exhaust Fan 40 CFM",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Kruger",
    "model": "40 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0031 · Dept: QC · Class: Support · Volt: 220 · kVA: 0.06 · Original name: 排气扇"
  },
  {
    "id": "LAB-001",
    "name": "Air Compressor Bolaite BLT-20A/10",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "上海望景供应链管理有限公司",
    "model": "Bolaite BLT-20A/10",
    "serial": "1900067",
    "installDate": "2019-06-16",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0032 · Dept: LAB1 · Class: Support · kVA: 0.084 · Remark: 二手 景望购入 · Original name: 空气压缩机"
  },
  {
    "id": "LAB-002",
    "name": "3-Phase High-Power Voltage Stabilizer CHNT TNSZ(SBW）-100",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "正泰",
    "model": "CHNT TNSZ(SBW）-100",
    "serial": "1802299",
    "installDate": "2011-06-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0090 · Dept: LAB1 · Class: Production · kVA: 0.084 · Working condition: No use · Remark: 10号楼1F机房---- · Original name: 三相大功率补偿式稳压器"
  },
  {
    "id": "LAB-003",
    "name": "Water-Cooled Chiller AW-10",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "深圳市安格斯机械有限公司",
    "model": "AW-10",
    "serial": "1802434",
    "installDate": "2010-08-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0091 · Dept: LAB1 · Class: Production · kVA: 0.084 · Working condition: No use · Original name: 水冷式冷水机"
  },
  {
    "id": "LAB-004",
    "name": "AHU",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0033 · Dept: LAB1 · Class: Support"
  },
  {
    "id": "LAB-005",
    "name": "Exhaust Fan 1,600 CFM",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "1,600 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0034 · Dept: LAB1 · Class: Support · Volt: 220 · kVA: 0.06 · Remark: Air compressor room · Original name: 排气扇"
  },
  {
    "id": "LAB-006",
    "name": "Air conditioner",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.00 KW 400 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0035 · Dept: LAB1 · Class: Support · Volt: 220 · kVA: 1.25 · Remark: Maintenance room"
  },
  {
    "id": "LAB-007",
    "name": "Air conditioner",
    "category": "LAB1",
    "location": "LAB1 Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "2.20 KW 800 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0036 · Dept: LAB1 · Class: Support · Volt: 220 · kVA: 2.75 · Remark: MDB room"
  },
  {
    "id": "OFF-001",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0037 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8"
  },
  {
    "id": "OFF-002",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0038 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8"
  },
  {
    "id": "OFF-003",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0039 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8"
  },
  {
    "id": "OFF-004",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0040 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8 · Remark: Sever room No ues"
  },
  {
    "id": "OFF-005",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.00 KW 400 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0041 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.25 · Remark: Accounting room No ues"
  },
  {
    "id": "OFF-006",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0042 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8 · Remark: Internal Meeting room"
  },
  {
    "id": "OFF-007",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.45 KW 500 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0043 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.8 · Remark: Reception room"
  },
  {
    "id": "OFF-008",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "2.00 KW 600 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0044 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 2.5 · Remark: Vip Room room"
  },
  {
    "id": "OFF-009",
    "name": "Air conditioner",
    "category": "OFFICE",
    "location": "OFFICE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "Carrier",
    "model": "1.00 KW 400 CFM",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0045 · Dept: OFFICE · Class: Support · Volt: 220 · kVA: 1.25 · Remark: External Meeting room"
  },
  {
    "id": "SUR-019",
    "name": "PRA blocker",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Satisloh Asia Limited",
    "model": "PRA",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0092 · Dept: SURFACE · Class: Production · Volt: 220"
  },
  {
    "id": "SUR-020",
    "name": "De-block",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Gino Optical (Shanghai)",
    "model": "Water boiling",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0093 · Dept: SURFACE · Class: Production · Volt: 220"
  },
  {
    "id": "SUR-021",
    "name": "Laser engraving machine",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "OptoTech Optikmaschinen GmbH",
    "model": "OTL-100",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0094 · Dept: SURFACE · Class: Production · Volt: 220"
  },
  {
    "id": "SUR-022",
    "name": "Swift -2",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Schneider",
    "model": "CCP-Swift",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0095 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1.5 · Working condition: 手动，温度10-15°C"
  },
  {
    "id": "SUR-023",
    "name": "Swift -3",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Schneider",
    "model": "CCP-Swift",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0096 · Dept: SURFACE · Class: Production · Volt: 380 · kVA: 1.5 · Working condition: 手动，温度10-15°C"
  },
  {
    "id": "SUR-024",
    "name": "Orbit-2E",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Satisloh Asia Limited",
    "model": "Orbit-2E",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0097 · Dept: SURFACE · Class: Production · Volt: 220"
  },
  {
    "id": "SUR-025",
    "name": "Chiller-1",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "SMC",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0046 · Dept: SURFACE · Class: Support · Volt: 220 · Remark: Blocker"
  },
  {
    "id": "SUR-026",
    "name": "Chiller-2",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "SMC",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0047 · Dept: SURFACE · Class: Support · Volt: 220 · Remark: Flash-1"
  },
  {
    "id": "SUR-027",
    "name": "Chiller-3",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "SMC",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0048 · Dept: SURFACE · Class: Support · Volt: 220 · Remark: Flash-2"
  },
  {
    "id": "SUR-028",
    "name": "Chiller-4",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "SMC",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0049 · Dept: SURFACE · Class: Support · Volt: 220 · Remark: Orbit water tank"
  },
  {
    "id": "SUR-029",
    "name": "Chiller-5",
    "category": "SURFACE",
    "location": "SURFACE Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "2P",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0050 · Dept: SURFACE · Class: Support · Volt: 220 · Remark: Orbit-1"
  },
  {
    "id": "TNT-009",
    "name": "UV Meter Spectrum 700VU",
    "category": "TINT",
    "location": "TINT Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Phantom",
    "model": "Spectrum 700VU",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0098 · Dept: TINT · Class: Production · Volt: 220 · Original name: UV meter"
  },
  {
    "id": "HC-021",
    "name": "Coating machine",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "SCL International",
    "model": "CDC-1000 (2)",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0099 · Dept: HC · Class: Production · Volt: 400 · kVA: 10.25"
  },
  {
    "id": "MC-012",
    "name": "De-humidifier",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DH-8150B",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0051 · Dept: MC · Class: Support"
  },
  {
    "id": "MC-013",
    "name": "Clean table180x130x193 cm + Ionizer",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0052 · Dept: MC · Class: Support"
  },
  {
    "id": "HC-022",
    "name": "OVEN (Small)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DHG-9053A",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0053 · Dept: HC · Class: Support"
  },
  {
    "id": "MC-014",
    "name": "OVEN (Big)",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DHG-9423A",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0054 · Dept: MC · Class: Support"
  },
  {
    "id": "HC-023",
    "name": "OVEN (Big)",
    "category": "HC",
    "location": "HC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DHG-9423A",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0055 · Dept: HC · Class: Support"
  },
  {
    "id": "MC-015",
    "name": "AR machine",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "DLX-1200 (2)",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0100 · Dept: MC · Class: Production · Volt: 400"
  },
  {
    "id": "MC-016",
    "name": "Clean table + Ionizer",
    "category": "MC",
    "location": "MC Area",
    "building": "Gino Thai Plant",
    "criticality": "Medium",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: SM0057 · Dept: MC · Class: Support"
  },
  {
    "id": "EDG-025",
    "name": "Electronic heater",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "NH-320F",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0101 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 0.75 · Working condition: Hot air mac 110°C"
  },
  {
    "id": "EDG-026",
    "name": "EZ-FIT (2)",
    "category": "EDGE",
    "location": "EDGE Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "MEI S.r.l.",
    "model": "ez fit, with scanner",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0102 · Dept: EDGE · Class: Production · Volt: 220 · kVA: 5 · Working condition: Water tank built in"
  },
  {
    "id": "QC-005",
    "name": "Pad Printing Machine",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "Codir转入",
    "model": "",
    "serial": "",
    "installDate": "2014-06-01",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0103 · Dept: QC · Class: Production · Volt: 220 · kVA: 0.4 · Remark: 10号楼1F质检---- · Original name: 移印机"
  },
  {
    "id": "QC-006",
    "name": "Auto Lensmeter",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "LM-7P/7",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0104 · Dept: QC · Class: Production"
  },
  {
    "id": "QC-007",
    "name": "Auto Lensmeter",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "LM-7P/7",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0105 · Dept: QC · Class: Production"
  },
  {
    "id": "QC-008",
    "name": "Auto Lensmeter",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "LM-7P/7",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0106 · Dept: QC · Class: Production"
  },
  {
    "id": "QC-009",
    "name": "Auto Lensmeter",
    "category": "QC",
    "location": "QC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "LM-7P/7",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0107 · Dept: QC · Class: Production"
  },
  {
    "id": "LOG-001",
    "name": "Card printer",
    "category": "LOGISTIC",
    "location": "LOGISTIC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "Zenis",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0108 · Dept: LOGISTIC · Class: Production"
  },
  {
    "id": "LOG-002",
    "name": "Label printer (1)",
    "category": "LOGISTIC",
    "location": "LOGISTIC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0109 · Dept: LOGISTIC · Class: Production"
  },
  {
    "id": "LOG-003",
    "name": "Label printer (2)",
    "category": "LOGISTIC",
    "location": "LOGISTIC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0110 · Dept: LOGISTIC · Class: Production"
  },
  {
    "id": "LOG-004",
    "name": "Voucher printer",
    "category": "LOGISTIC",
    "location": "LOGISTIC Area",
    "building": "Gino Thai Plant",
    "criticality": "High",
    "status": "Running",
    "health": 90,
    "manufacturer": "",
    "model": "",
    "serial": "",
    "installDate": "",
    "lastPM": "",
    "nextPM": "",
    "mtbfDays": 0,
    "runHours": 0,
    "openWOs": 0,
    "notes": "Old ID: PM0111 · Dept: LOGISTIC · Class: Production"
  }
];
