/* ============================================================
   CMMS DATA FILE — Work Orders
   Sample work orders referencing real imported machine IDs.
   Editable in-app (Work Orders module); plain JSON in a .js wrapper.
   ============================================================ */
window.CMMS_DB = window.CMMS_DB || {};
window.CMMS_DB.workOrders = [
  {
    "id": "WO-0001",
    "title": "Chiller not cooling — compressor fault",
    "assetId": "SUR-014",
    "type": "Breakdown",
    "priority": "High",
    "status": "In Progress",
    "technician": "S. Wattana",
    "requestedBy": "Surface Supervisor",
    "created": "2026-05-12",
    "due": "2026-05-14",
    "completed": "",
    "description": "SUR-014 chiller stopped cooling. Suspect compressor or refrigerant loss. Surfacing line water temperature rising.",
    "resolution": "",
    "labourHrs": 3.5,
    "downtimeHrs": 18
  },
  {
    "id": "WO-0002",
    "title": "Conventional polisher — spindle vibration",
    "assetId": "SUR-002",
    "type": "Corrective",
    "priority": "Medium",
    "status": "Open",
    "technician": "P. Niran",
    "requestedBy": "Operator A.",
    "created": "2026-05-13",
    "due": "2026-05-16",
    "completed": "",
    "description": "Toro-X-2S polisher showing abnormal spindle vibration during cycle. Inspect bearings and mounts.",
    "resolution": "",
    "labourHrs": 0,
    "downtimeHrs": 0
  },
  {
    "id": "WO-0003",
    "title": "Monthly PM — Air compressor",
    "assetId": "LAB-001",
    "type": "Preventive",
    "priority": "Medium",
    "status": "Open",
    "technician": "T. Somchai",
    "requestedBy": "Maintenance Plan",
    "created": "2026-05-10",
    "due": "2026-05-15",
    "completed": "",
    "description": "Bolaite BLT-20A monthly service: drain condensate, check oil, inspect belts and air filter.",
    "resolution": "",
    "labourHrs": 0,
    "downtimeHrs": 0
  },
  {
    "id": "WO-0004",
    "title": "Edger calibration check",
    "assetId": "EDG-003",
    "type": "Inspection",
    "priority": "Low",
    "status": "On Hold",
    "technician": "K. Anong",
    "requestedBy": "QC Dept",
    "created": "2026-05-08",
    "due": "2026-05-12",
    "completed": "",
    "description": "Frame scanner reading drift reported. On hold pending calibration jig from supplier.",
    "resolution": "",
    "labourHrs": 1.0,
    "downtimeHrs": 0
  },
  {
    "id": "WO-0005",
    "title": "Tinting machine cylinder leak",
    "assetId": "TNT-001",
    "type": "Breakdown",
    "priority": "High",
    "status": "Open",
    "technician": "P. Niran",
    "requestedBy": "Tint Supervisor",
    "created": "2026-05-13",
    "due": "2026-05-14",
    "completed": "",
    "description": "Cylinder 7 on 12-cylinder tinting machine leaking dye. Isolate cylinder and replace seal.",
    "resolution": "",
    "labourHrs": 0,
    "downtimeHrs": 4
  },
  {
    "id": "WO-0006",
    "title": "Quarterly PM — Industrial dehumidifier",
    "assetId": "HC-002",
    "type": "Preventive",
    "priority": "Low",
    "status": "Open",
    "technician": "T. Somchai",
    "requestedBy": "Maintenance Plan",
    "created": "2026-05-11",
    "due": "2026-05-20",
    "completed": "",
    "description": "YDA-89 dehumidifier quarterly service: clean coils, replace filter, check drainage.",
    "resolution": "",
    "labourHrs": 0,
    "downtimeHrs": 0
  },
  {
    "id": "WO-0007",
    "title": "Ultrasonic cleaner — heater not working",
    "assetId": "HC-003",
    "type": "Corrective",
    "priority": "Medium",
    "status": "In Progress",
    "technician": "S. Wattana",
    "requestedBy": "HC Operator",
    "created": "2026-05-12",
    "due": "2026-05-15",
    "completed": "",
    "description": "Single-tank ultrasonic cleaner heating element not reaching set temperature. Test element and thermostat.",
    "resolution": "",
    "labourHrs": 2.0,
    "downtimeHrs": 2
  },
  {
    "id": "WO-0008",
    "title": "Sandblasting machine nozzle replacement",
    "assetId": "MC-003",
    "type": "Corrective",
    "priority": "Medium",
    "status": "Completed",
    "technician": "K. Anong",
    "requestedBy": "MC Supervisor",
    "created": "2026-05-05",
    "due": "2026-05-07",
    "completed": "2026-05-07",
    "description": "SY-1610A sandblaster nozzle worn, inconsistent finish.",
    "resolution": "Replaced nozzle and checked air pressure. Test pieces passed QC. Returned to service.",
    "labourHrs": 1.5,
    "downtimeHrs": 3
  },
  {
    "id": "WO-0009",
    "title": "Monthly PM — Voltage stabilizer",
    "assetId": "MC-001",
    "type": "Preventive",
    "priority": "Low",
    "status": "Completed",
    "technician": "T. Somchai",
    "requestedBy": "Maintenance Plan",
    "created": "2026-05-02",
    "due": "2026-05-05",
    "completed": "2026-05-05",
    "description": "3-phase voltage stabilizer monthly inspection: terminals, cooling fan, output voltage log.",
    "resolution": "All readings within tolerance. Tightened two terminals. No issues.",
    "labourHrs": 1.0,
    "downtimeHrs": 0
  },
  {
    "id": "WO-0010",
    "title": "Air compressor belt squeal",
    "assetId": "LAB-001",
    "type": "Corrective",
    "priority": "High",
    "status": "Completed",
    "technician": "S. Wattana",
    "requestedBy": "Operator B.",
    "created": "2026-04-28",
    "due": "2026-04-30",
    "completed": "2026-04-29",
    "description": "Loud squeal from compressor on startup, suspected slipping belt.",
    "resolution": "Replaced drive belt and re-tensioned. Squeal resolved.",
    "labourHrs": 2.0,
    "downtimeHrs": 1
  },
  {
    "id": "WO-0011",
    "title": "Frame scanner — annual inspection",
    "assetId": "EDG-003",
    "type": "Inspection",
    "priority": "Low",
    "status": "Open",
    "technician": "Unassigned",
    "requestedBy": "Maintenance Plan",
    "created": "2026-05-09",
    "due": "2026-05-25",
    "completed": "",
    "description": "Annual inspection of FUJI-300TX frame scanner: clean optics, verify accuracy against reference frame.",
    "resolution": "",
    "labourHrs": 0,
    "downtimeHrs": 0
  }
];
